### ISSUE TITLE
[question]: about require this package

### ISSUE THREAD

**Issue by youyiqin** [sensedeep/onetable-migrate#2]
Hi there.
this is my code:
```js
const Migrate = require('onetable-migrate')
```
`Migrate` just a object.I can not use it like this: "new Migrate({...})"
Right?Your readme.md show us some code like that: " const xx = new Migrate()".
But, `Migrate` is a object,I gotto use the default property.
```js
const Migrate = require('onetable-migrate').default
```
My English is poor.Maybe my word is hard to understand.
Thanks!

**Comment by mobsense** [comment]
Yes, you are right. Currently it is using an "export default class Migrate"

So you need to import with 

    const Migrate = require('onetable-migrate').default

or

    import Migrate from 'onetable-migrate'

We are going to fix this in 0.7.1 so that you won't need the ".default".

It will then look like:

    const {Table} = require('dynamodb-onetable')
    const {Migrate} = require('onetable-migrate')

or 

    import {Table} from 'dynamodb-onetable'
    import {Migrate} from 'onetable-migrate'

this

**Comment by youyiqin** [comment]
@mobsense thanks.I know.
😂 
I just want to use:
```js
const Migrate  = require('onetable-migrate')
```
I just thinks the ".default" is ugly.
So, can we export default class like before?
and write code like this:
```js
// commonjs
const Migrate = require('onetable-migrate')
// or
// esm
import Migrate from 'onetable-migrate'
```
source code contains `default export class`
😁

**Comment by mobsense** [comment]
We prefer

const {Migrate} = require('onetable-migrate')

for 2 reasons:

* Consistency with `const {Model, Table} = require('dynamodb-onetable')
* It provides an upwards migration path if we need to export other classes

Migrate is not a plain object. It is an ES6 class.

So this solution isn't as simple as your `const Migrate = require...`, but ESM is the future.

Let me know if you have strong push back or if I'm missing something.

**Comment by youyiqin** [comment]
thanks.
